### ISSUE TITLE
Github doesn't have PMs...

### ISSUE THREAD

**Issue by naryl** [nauar/homepage#1]
I have a feeling I know you really well from somewhere. This may be a long shot but were you known in Xonotic as Grunt?

**Comment by nauar** [comment]
Hello @naryl ,

Long time no see! Yes, you're right. I'm Grunt! :smile: I hope everything is well.

Nice to find you here and keep in touch with you!

**Comment by naryl** [comment]
I have better memory than I thought. :D
Were you looking for people nicknamed "naryl" or did you find me randomly?
Also, I'm on BOT's Discord group anyway. :D As a "botrepublic reservist".
Everything's well. I hope you're doing good too. :)

**Comment by nauar** [comment]
I searched by "naryl" and then it was easy to find you... your full name and so many projects in Common Lisp... really easy! ;)

I don't use Discord so much, I still use IRC. :P
